server:
  port: 8081
  tomcat:
    uri-encoding: utf-8
spring:
  application:
    name: TestExport
  profiles:
    active:
logging:
  ##可以直接在yaml文件里指定日志输出路径
  ##也可以在resources下新建一个名为logback-spring.xml的文件，指定日志输出路径
  ##两者都是叠加
  file: logs/TestExport.log
  level: info
mybatis:
  configuration:
    default-fetch-size: 100
    default-statement-timeout: 30
  mapper-locations: classpath*:mybatis/mapper/*.xml